### ISSUE TITLE
Fail on Vagrant up

### ISSUE THREAD

**Issue by matthewkeath** [roots/bedrock-ansible#171]
Getting this when a vagrant up. Any ideas?

```
/Users/lornaberry/development/melbournefamilyhub.com.au/wordpresscms-ansible/Vagrantfile:25:in `block (2 levels) in <top (required)>': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/lornaberry/development/melbournefamilyhub.com.au/wordpresscms-ansible/Vagrantfile:25:in `each'
	from /Users/lornaberry/development/melbournefamilyhub.com.au/wordpresscms-ansible/Vagrantfile:25:in `flat_map'
	from /Users/lornaberry/development/melbournefamilyhub.com.au/wordpresscms-ansible/Vagrantfile:25:in `block in <top (required)>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/v2/loader.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:103:in `block (2 levels) in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:97:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:97:in `block in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:94:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:94:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:691:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:691:in `vagrantfile'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:441:in `host'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:207:in `block in action_runner'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:33:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:33:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:428:in `hook'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:673:in `unload'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:177:in `ensure in <main>'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:177:in `<main>'
```

**Comment by swalkinshaw** [comment]
It's failing on this [line](https://github.com/roots/bedrock-ansible/blob/238ca2790e90b39944228a2cc10050a8f9bba8d9/Vagrantfile#L26).

It means something is misconfigured in your `group_vars/development` (regarding `wordpress_sites` file. It should look something like this https://github.com/roots/bedrock-ansible/blob/238ca2790e90b39944228a2cc10050a8f9bba8d9/group_vars/development

**Comment by tremby** [comment]
I had the same thing with a badly-formatted yaml file. This case could do with a better error message.
